# local environment.
version: '3'

services:
  nginx:
    container_name: untitled_app_nginx
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 81:80
    volumes:
      - ./www/public:/var/www/public:cached
      - ./www/storage/app:/var/www/public/storage
    depends_on:
      - php
    environment:
      TZ: Asia/Tokyo

  php:
    container_name: untitled_app_php
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./www:/var/www
    links:
      - database

  database:
    container_name: untitled_app_pgsql
    build:
      context: ./
      dockerfile: docker/database/Dockerfile
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - 54321:5432
    environment:
      POSTGRES_DB: untitled
      POSTGRES_USER: untitled_user
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    command: -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    logging:
      options:
        max-size: "10k"
        max-file: "5"

  # テーブル定義書　(execute after db:migrate)
  tbls:
    container_name: untitled_app_dbdoc
    image: k1low/tbls:latest
    volumes:
      - ./:/work
    command: doc mysql://untitled_user:secret@untitled_app_mysqld:3306/untitled ./doc/schema --force
    profiles:
      - dbdoc

volumes:
  pgsql_data:
    driver: local
